### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by moh1122** [Alterplay/APAddressBook#101]
hello
Thanks for the tut its great but im getting those errors while building your project any clue how to solve them:
diff: /../Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

Thank you awaiting your reply

**Comment by keith** [comment]
This is a CocoaPods issue not related to this library.

**Comment by keith** [comment]
Also as the error message states you should be able to rerun `pod install` to fix this problem.

**Comment by moh1122** [comment]
can you plz tell me how to do the pod install

**Comment by belkevich** [comment]
[Cocoapods guide](https://guides.cocoapods.org/using/index.html)
