### ISSUE TITLE
Build Issues - parse errors

### ISSUE THREAD

**Issue by inna215** [Alterplay/APAddressBook#103]
I ran pod install with no issues.  Opened my project and tried to build.  I haven't tried using this yet. There are lots of compiler errors in APAddressBook.h - see examples below:

All "typedef" lines at the top are showing one of the following errors

expected ')'
expected '>'

this line has about 5 different parse errors

@property (nullable, nonatomic, strong) NSArray <NSSortDescriptor *> *sortDescriptors;

Am I doing something wrong?

**Comment by inna215** [comment]
xCode version 6.4
I'm writing in Swift but I have other objective-C libraries and they compile fine.

**Comment by belkevich** [comment]
xCode 6.4 doesn't support generics. Thats why you get this errors.
You can use `APAddressBook` version 0.1.14. It doesn't use generics.
But if you Swift developer, I would recommend you to update to xCode 7 and unlock full power of Swift 2.0
