### ISSUE TITLE
Contacts have no emails when building on Xcode 7 ios 8 and iOS 9

### ISSUE THREAD

**Issue by johannwerner** [Alterplay/APAddressBook#104]
The emails array for APContact is empty despite contacts having emails. Tested on simulator and device.

**Comment by belkevich** [comment]
Please, share your code.

**Comment by johannwerner** [comment]
APAddressBook *addressBook = [[APAddressBook alloc] init];
            [addressBook loadContacts:^(NSArray<APContact *> *contacts, NSError *error) {
              if (!error) {
                  for (APContact *contact in contacts) {
                      NSLog(@"%@ %lu",contact.name.compositeName,contact.emails.count);
                      for (APEmail *email in contact.emails) {
                          NSLog(@"%@",email.address);
                      }
                  }
              } else {
                  [self displayErrorMessageWithError:error];
              }
            }];

**Comment by belkevich** [comment]
You didn't set `fieldsMask`. Please, read [README](https://github.com/Alterplay/APAddressBook/blob/master/README.md) file.

**Comment by johannwerner** [comment]
Sorry my bad. Apologies.
