### ISSUE TITLE
APEmail is not a collection

### ISSUE THREAD

**Issue by ghazel** [Alterplay/APAddressBook#105]
We had some search code using NSPredicate which worked great: `"ANY SELF.emails CONTAINS[c] %@"`. However, after an upgrade to APAddressBook 0.2.x, we get:

```
 *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Can't use in/contains operator with collection <APEmail: 0x7fe0795230c0> (not a collection)'
```

We're going to stick on 0.1.14 until this works again.

**Comment by belkevich** [comment]
Read [0.1.x to 0.2.x migration guide](https://github.com/Alterplay/APAddressBook/wiki/0.1.x-to-0.2.x-migration-guide)
