### ISSUE TITLE
Easiest way to serialize APContact to NSDictionary?

### ISSUE THREAD

**Issue by JeanLebrument** [Alterplay/APAddressBook#108]
Hi,

I wondering what is the easiest way to serialize APContact to NSDictionary?

Thanks!

**Comment by belkevich** [comment]
Hi,
Look at this library - [EasyMapping](https://github.com/EasyMapping/EasyMapping).

**Comment by JeanLebrument** [comment]
Would you be interested if I submit a pull request with the using of this library in this project to be able to serialize easily `APContact`?

**Comment by belkevich** [comment]
Better be if you create your own repo (for instance `APContact+EasyMapping`) and submit it to cocoapods. And I'll put link to it in README.

**Comment by JeanLebrument** [comment]
I will answer to this issue with the link to my repo!

**Comment by belkevich** [comment]
Ok

**Comment by JeanLebrument** [comment]
Hey! Done: https://github.com/JeanLebrument/APContact-EasyMapping

**Comment by belkevich** [comment]
Looks good! I'll add link soon.
P.S. What you think about add method like `serializeToDictionary`? So developer will not interact directly with `EasyMapping`, only with your category.

**Comment by JeanLebrument** [comment]
Done :)

**Comment by belkevich** [comment]
Great!

**Comment by belkevich** [comment]
[Done](https://github.com/Alterplay/APAddressBook/blob/master/README.md#apcontact-serialization)

Also, could you add readme with short description and example to your repo?

**Comment by JeanLebrument** [comment]
I already created a really basic example and I just added a README with explanations.

**Comment by belkevich** [comment]
ok

**Comment by belkevich** [comment]
I've posted update to [twitter](https://twitter.com/okolodev/status/664822953050251265)

**Comment by JeanLebrument** [comment]
Thanks!

**Comment by JeanLebrument** [comment]
Thanks!
