### ISSUE TITLE
Extract addresses with labels

### ISSUE THREAD

**Issue by ikonst** [Alterplay/APAddressBook#113]
Addresses also have labels such as Home and Work. There should be an API to extract them, just like for E-mail labels.

**Comment by belkevich** [comment]
Done. Check out new version 0.2.2

**Comment by ikonst** [comment]
:tada:

**Comment by pushian** [comment]
@belkevich The contact.address is always nil.

**Comment by belkevich** [comment]
@pushian 
Do you set `fieldMask` property with `Address`?
