### ISSUE TITLE
IOS 9 have lot of ABAddressBookRef warnings, is there going to be an update for this.

### ISSUE THREAD

**Issue by vickyrappier** [Alterplay/APAddressBook#114]
Hi Kiev,

There are many IOS 9 warnings since I updated my project to support IOS 9. Are you planning to make this iOS 9 compatible.

Great library though.

**Comment by belkevich** [comment]
Hi,
It's a duplicate of [issue#91](https://github.com/Alterplay/APAddressBook/issues/91)
