### ISSUE TITLE
Linked Contacts optimisation and handling guidance required

### ISSUE THREAD

**Issue by vickyrappier** [Alterplay/APAddressBook#115]
Hello Kiev,

Although I see that the there is a good handling to find the linked contacts. Please can you guide us more efficient way to handle the linked contacts.

Here is my code that I have doing to handle the linked contacts in my case. But if the library that is hardline to give me only the contacts same as I see in IOS Contacts App and linked shown as array to that APContact object will be great.

Please advice me a way to proceed.

//Code for the load contacts
{
    //Check once always in app
    
    [tempLinkedContacts removeAllObjects];
    
    if(!self.addressBook)
    {
        [self initialiseAddressBook];
    }

    [[NSNotificationCenter defaultCenter] postNotificationName:kContactLoadStartingNotificationKey object:nil];
    

    NSManagedObjectContext *privateContext = [[NSManagedObjectContext alloc] initWithConcurrencyType:NSPrivateQueueConcurrencyType];
    
    [privateContext setParentContext:self.mainObjectContext];

    
  [self.addressBook loadContactsOnQueue:queue completion:^(NSArray<APContact *> * _Nullable contacts, NSError * _Nullable error) //    [self.addressBook loadContacts:^(NSArray *contacts, NSError *error)
     {
         NSDate *latestModifedContactDate = nil;
         
         if(!tempLinkedContacts)
             [tempLinkedContacts removeAllObjects];
         else
             tempLinkedContacts = [[NSMutableArray alloc] init];

         int counter = 0;
         
         NSMutableArray *syncingcontacts = [[NSMutableArray alloc] init];
         
        for (APContact *apContactObject in contacts) {
            
            
             
             if(apContactObject.linkedRecordIDs.count > 0)
             {
                 //check if any of the link contacts is already in the DB then dont add this contacts
                 BOOL isLinkedContactsInDb = [[CLBizManager sharedManager] checkIdContactExistithABIds:apContactObject.linkedRecordIDs managedContext:privateContext];
                 
                 if(!isLinkedContactsInDb)
                 {
                     DLog(@"Contact Added[L]:\t[%@]|[%@]",apContactObject.name.compositeName,apContactObject.recordID);

                     [[CLBizManager sharedManager] addABContact:apContactObject andManagedContext:privateContext];
                     
                     for (APPhone *phoneWithLabelVO in apContactObject.phones) {
                         
                         NSString *number = [[CLUtilities sharedManager] getFilteredPhoneNumber:phoneWithLabelVO.number];
                         
                         if([[CLUtilities sharedManager] isValidPhoneNumber:number] && ![syncingcontacts containsObject:number])
                         {
                             [syncingcontacts addObject:number];
                         }
                     }
                 }
             }
             else
             {
                 //Straight update/add the  contact
                [[CLBizManager sharedManager] addABContact:apContactObject andManagedContext:privateContext];
                DLog(@"Contact Added[S]:\t[%@]|[%@]",apContactObject.name.compositeName,apContactObject.recordID);
                 
                 
                 for (APPhone *phoneWithLabelVO in apContactObject.phones) {
                     
                     NSString *number = [[CLUtilities sharedManager] getFilteredPhoneNumber:phoneWithLabelVO.number];
                     
                     if([[CLUtilities sharedManager] isValidPhoneNumber:number] && ![syncingcontacts containsObject:number])
                     {
                         [syncingcontacts addObject:number];
                     }
                 }
             }

             if(!latestModifedContactDate || [latestModifedContactDate compare:apContactObject.recordDate.modificationDate] == NSOrderedAscending)
                 latestModifedContactDate = apContactObject.recordDate.modificationDate;
             
            [[NSNotificationCenter defaultCenter] postNotificationName:kContactLoadProgressNotificationKey object:[NSDictionary dictionaryWithObjects:@[[NSNumber numberWithInt:counter],[NSNumber numberWithInteger:[contacts count]]] forKeys:@[kContactNoKey,kContactTotalCountKey]]];

            
            counter++;
             
         }
         
         [[CLUtilities sharedManager] setContactStoredTime:latestModifedContactDate];
         
         [[CLBizManager sharedManager] performGroupMemberNameUpdatesForContext:privateContext];
         
         [privateContext performBlock:^{
             
             NSError *childerror = nil;
             
             if (![privateContext save:&childerror]) {

                 DLog(@"Error saving chile context: %@\n%@", [childerror localizedDescription], [childerror userInfo]);
                 
             }
             else
             {
                 [self.mainObjectContext performBlock:^{

                     NSError *parentError;
                     if (![self.mainObjectContext save:&parentError]) {
                         DLog(@"Error saving chile context: %@\n%@", [parentError localizedDescription], [parentError userInfo]);
                     }
                     
                     [[NSNotificationCenter defaultCenter] postNotificationName:kContactLoadCompleteNotificationKey object:[NSDictionary dictionaryWithObjects:@[[NSNumber numberWithInt:counter],[NSNumber numberWithInteger:[contacts count]]] forKeys:@[kContactNoKey,kContactTotalCountKey]]];
                     
                     [[NSNotificationCenter defaultCenter] postNotificationName:kContactSyncStartedNotificationKey object:nil];
                     
                     //Sync back all numbers
                     [[CLBizManager sharedManager] syncApplicationContactsForNumbers:syncingcontacts];

                 }];

             }
                 
         }];

     }]; //LoadContacts end
}

**Comment by belkevich** [comment]
Hello,

Unfortunately, there is no way to hide linked contacts like in `Contacts.app`.
Read more at [issue#18](https://github.com/Alterplay/APAddressBook/issues/18)
