### ISSUE TITLE
APContact wont be retrived if it contains linked contacts

### ISSUE THREAD

**Issue by peterpaulis** [Alterplay/APAddressBook#119]
i always get nil record from loadContactByRecordID when i load a contact which has linked contacts

<pre>
- (void)peoplePickerNavigationController:(ABPeoplePickerNavigationController*)peoplePicker didSelectPerson:(ABRecordRef)person {
    
    [self.navigationController dismissViewControllerAnimated:YES completion:^{
        
        ABRecordID recordID = ABRecordGetRecordID(person);
        [self.addressBook loadContactByRecordID:@(recordID) completion:^(APContact * contact) {
...
</pre>

note that i have successfully requested access before

<pre>
        APAddressBook *addressBook = [[APAddressBook alloc] init];
        addressBook.fieldsMask = APContactFieldAll;
        self.addressBook = addressBook;
[self.addressBook requestAccess:^(BOOL granted, NSError * _Nullable error) {
 </pre>

**Comment by peterpaulis** [comment]
i also opened a question here http://stackoverflow.com/questions/34994679/abaddressbookgetpersonwithrecordid-returns-null-when-contact-has-linked-contacts

**Comment by peterpaulis** [comment]
this is maybe due to the fact that the AB methods are deprecated and CN should be used instead

**Comment by belkevich** [comment]
1) Why are you using `ABRecordRef ` instead of `recordID` field in `APContact`?
2) Are you sure that `ABRecordRef` is valid? Does your `ABAddressBookRef` still exists on this step?

**Comment by peterpaulis** [comment]
i'am getting the ID with ABRecordID recordID = ABRecordGetRecordID(person); is there a better approach?

i can confirm that on iOS9 the ABAddressBookGetPersonWithRecordID is broken on contacts with linked contacts (working ok on 7-8)

using the new CN seems to be the solution for iOS9, however the whole APContact is based on AB :(

**Comment by belkevich** [comment]
> i'am getting the ID with ABRecordID recordID = ABRecordGetRecordID(person); is there a better approach?

Sure, you can use `recordID` field of `APContact`. Why are you using `AddressBook.framework` directly without `APAddressBook`?

> i can 100% confirm that on iOS9 the ABAddressBookGetPersonWithRecordID is broken on contacts with linked contacts (working ok on 7-8)

Sorry, I don't understand you. You can't get `ABRecordRef` by `ABRecordID`?

**Comment by peterpaulis** [comment]
Sure, you can use recordID field of APContact. Why are you using AddressBook.framework directly without APAddressBook?

-> the delegate method for apple people picker returns ABRecordRef which i use to get the ID, please see the code

<pre>
- (void)peoplePickerNavigationController:(ABPeoplePickerNavigationController*)peoplePicker didSelectPerson:(ABRecordRef)person {
    
    [self.navigationController dismissViewControllerAnimated:YES completion:^{
        
        ABRecordID recordID = ABRecordGetRecordID(person);
        [self.addressBook loadContactByRecordID:@(recordID) completion:^(APContact * contact) {
...
</pre>

i'am not using ABAddressBookGetPersonWithRecordID, but APContact is using it internally and i can confirm that this method is broken on iOS9

**Comment by peterpaulis** [comment]
i can get the ID from ABRecordID recordID = ABRecordGetRecordID(person);
        
but when i send it to [self.addressBook loadContactByRecordID... which than calls ABAddressBookGetPersonWithRecordID internally, which is broken for linked contacts, co NULL is returned (even when on iOS7-8 a contact is returned) 

so no contact is loaded when the contact has a linked contact and it's run on iOS9!!!

**Comment by belkevich** [comment]
I've made some changes in example app to check how it works with linked contacts. So, I've added filter to receive contacts that have linked contacts. And then load them with `recordID`.
It works fine on my iPhone (iOS 9.2.1)

Follow this steps:
1) Clone this repo and checkout branch named `test`
2) Open objective-c example app and run it

Does it work for you?

**Comment by peterpaulis** [comment]
The DT classes seems to be missing

**Comment by peterpaulis** [comment]
the example displays the contact with the linked contact, than maybe a problem is with the ABPeoplePickerNavigationController will do an example too

**Comment by peterpaulis** [comment]
ok, i got it... found out to be some memory issue... moving the ABRecordGetRecordID out of the completion blocked, solved the issue... for linked contacts on iOS9, the ABRecordRef got invalidated in the completion block, and therefore recordID was garbage, which didn't point to a contact... quite strange

<pre>
- (void)peoplePickerNavigationController:(ABPeoplePickerNavigationController*)peoplePicker didSelectPerson:(ABRecordRef)person {

    ABRecordID recordID = ABRecordGetRecordID(person);
    [self.navigationController dismissViewControllerAnimated:YES completion:^{

        [self.addressBook loadContactByRecordID:@(recordID) completion:^(APContact * contact) {
</pre>
