### ISSUE TITLE
[ Swift ]Contacts list is empty even loading contacts successfully 

### ISSUE THREAD

**Issue by dongmai** [Alterplay/APAddressBook#121]
Hi everyone, 

I downloaded the zip file and try the two examples for objective c & Swift. The Objective C example can load and display contacts successfully but Swift example cannot - the list always be empty even the loadContacts() function found contacts (I checked via debugging).

I also done some debugs and realize that a bunch of functions of table delegate/ data source in DTTableViewManager.swift file are never called.

Can someone please take a look on that. (Sorry for my bad English).

Thanks.

**Comment by dongmai** [comment]
Sorry, Seems this wrapper doesn't support iOS 9 yet.

**Comment by belkevich** [comment]
APAddressBook use AddressBook.framework which is deprecated in iOS9. But it still works on any version of iOS.
