### ISSUE TITLE
how to sort by last contact date?

### ISSUE THREAD

**Issue by ionutsebastian824** [Alterplay/APAddressBook#122]
I know I need to use sortDescriptors but not sure what key needs to be used for last contact date. addressBook.sortDescriptors = @[[NSSortDescriptor sortDescriptorWithKey:@"" ascending:NO];
please help

**Comment by belkevich** [comment]
'APContact' has many dates like contact birthday, record creation and modification dates and array of dates associated with contact. Which of date do you mean?
Here is example how to sort contacts by record creation date
```objective-c
addressBook.sortDescriptors = @[[NSSortDescriptor sortDescriptorWithKey:@"recordDate.creationDate" ascending:NO];
```

**Comment by ionutsebastian824** [comment]
Thanks for your reply, @belkevich 
I wanted to get the contacts sorted by the last contact date which is the latest date accessed to the contact

**Comment by belkevich** [comment]
There is no such record field like 'last access' date. But you can try record modification date
```objective-c
addressBook.sortDescriptors = @[[NSSortDescriptor sortDescriptorWithKey:@"recordDate.modificationDate" ascending:NO];
```

**Comment by ionutsebastian824** [comment]
ok, thanks
