### ISSUE TITLE
iOS 10 - Request permission

### ISSUE THREAD

**Issue by Artimuss** [Alterplay/APAddressBook#132]
Hi,

I had an issue (screenshot below) when I enter in this method :
`[addressBook loadContactsOnQueue:dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0) completion:^(NSArray *contacts, NSError *error) {
         if (!error)
        {
           //Do smthg
        }
       else
       {
          NSLog(@"Error : %@", error);
       }
}];`

![capture d ecran 2016-07-29 a 10 15 27](https://cloud.githubusercontent.com/assets/15651664/17242092/98bd5b64-5575-11e6-9a9e-f43d7c3e5380.png)

This is due to iOS 10. To solve it, you need to add "Privacy - Contacts Usage Description" in your Info.plist, you can leave the value empty or put a message if you want.

Maybe you can add something about it in the README.

Have a nice day !

**Comment by belkevich** [comment]
Hi @Artimuss,

Thank you for feedback. I definitely add this to README after a short research about this flag

**Comment by Artimuss** [comment]
Hi @belkevich,

No problem!

**Comment by belkevich** [comment]
Done.
@Artimuss, thank you for issue
