### ISSUE TITLE
filter by phoneNumber

### ISSUE THREAD

**Issue by mkaya93** [Alterplay/APAddressBook#134]
Hi,

I'm trying to filter contacts by phone number. Which method should I use for this.

Thanks

**Comment by belkevich** [comment]
Hi,

How exactly you want to filter contacts? Do you want to remove contacts without phone number?

**Comment by mkaya93** [comment]
No I just want to find contact with phone number. So How can I do that ?

**Comment by belkevich** [comment]
```objective-c
addressBook.filterBlock = ^BOOL(APContact *contact)
{
    for (APPhone *phone in contact.phones)
    {
        if ([phone.number isEqualToString:@"1234567890"])
        {
            return YES;
        }
    }
    return NO;
};
```

**Comment by belkevich** [comment]
Does it helps?

**Comment by mkaya93** [comment]
Actually now its crashing on some contacts which is not have phone numbers. I'm trying to solve it

**Comment by belkevich** [comment]
Ok, feel free to reopen this issue if you need it
