### ISSUE TITLE
How to get just the contacts 'iPhone' or 'mobile' numbers?

### ISSUE THREAD

**Issue by zilions** [Alterplay/APAddressBook#141]
The phone numbers returned are all types such as `home`. Sometimes these numbers are not wanted if the address book list returned is going to be used for SMS purposes.

Is it possible to filter them out and just get phone numbers that are in the fields `mobile` or `iPhone`?

**Comment by belkevich** [comment]
Unfortunately, it's impossible. Contact's filter applies to whole contact not contact's field
