### ISSUE TITLE
url property of APSocialProfile is declared as NSURL but is an NSString

### ISSUE THREAD

**Issue by popwarsweet** [Alterplay/APAddressBook#144]
The `url` property of `APSocialProfile` is declared as an NSURL, but is assigned an NSString instance. This causes a crash when accessing this property. The crash is `-[__NSCFString isFileReferenceURL]: unrecognized selector sent to instance`

**Comment by belkevich** [comment]
Thank you!
I'll check it

**Comment by belkevich** [comment]
Fixed.
Check out 0.3.0 version
