### ISSUE TITLE
Is there a unique property for each user?

### ISSUE THREAD

**Issue by ccoeder** [Alterplay/APAddressBook#146]
I think contact.recordID is not a unique property or I do not fully understand, can someone help me?

**Comment by belkevich** [comment]
@ccoeder `APAdreesBook` use `AddressBook.framework`and according to the [apple's documentation](https://developer.apple.com/reference/addressbook/1614734-abrecordgetrecordid) it should be unique.

**Comment by ccoeder** [comment]
`NSLog(@"%@", contact.recordID);`

This is what happens when you try it like this:

![screen shot 2016-12-06 at 13 55 04](https://cloud.githubusercontent.com/assets/10330468/20923050/45f477d8-bbb3-11e6-84c1-e71dd385ef67.png)

**Comment by belkevich** [comment]
I don't see any duplicates))

**Comment by ccoeder** [comment]
Is that something like auto incerement?

**Comment by belkevich** [comment]
I don't know for sure, but it looks like auto incremented field in most databases

**Comment by ccoeder** [comment]
It's not what I want then. Is there a way I can find the number of the person (the owner of the phone) from within the entire list?

**Comment by belkevich** [comment]
Sorry, I don't understand. What exactly you want to do?

**Comment by ccoeder** [comment]
I am trying to make an application, and in this application I show the user's contacts, I record in the database who is selected when someone selects the user's guide. What I need is the phone number of the person who is using the application so I can distinguish it from the others.

**Comment by belkevich** [comment]
So, you want to find contact record of iPhone/iPad owner? 
Unfortunately, `APAddressBook` doesn't support such functional.
But you can try [Contacts API](https://developer.apple.com/reference/contacts). May be it helps

**Comment by ccoeder** [comment]
By the way your pod is amazing, thanks!

**Comment by belkevich** [comment]
Thank you!
Happy coding!
