### ISSUE TITLE
Does this work when the app is in background?

### ISSUE THREAD

**Issue by techwizardg** [Alterplay/APAddressBook#147]
This is not an issue and did not know where to post and hence asking it here. I need to be notified on phone book changes even my app is running in background and need to be notified on changes when app is terminated and reopened again?
How do i go about doing it?

**Comment by belkevich** [comment]
> I need to be notified on phone book changes even my app is running in background

Try this:
```
// start observing
[addressBook startObserveChangesWithCallback:^
{
    // reload contacts
}];
```
This callback will run when you restore app from background

> and need to be notified on changes when app is terminated and reopened again

You can store contacts from previous app session and compare them with contacts from current app session.

**Comment by techwizardg** [comment]
Thanks and will close it

**Comment by vijayaa** [comment]
This method is not getting called when app is in foreground/background
[addressBook startObserveChangesWithCallback:^
{
    // reload contacts
}];

**Comment by belkevich** [comment]
@vijayaa moved to [issue](https://github.com/Alterplay/APAddressBook/issues/149)
