### ISSUE TITLE
Can not get business name

### ISSUE THREAD

**Issue by diegothucao** [Alterplay/APAddressBook#151]
Hi mate,
I am using this library and I discover that this cannot get business name, I mean the company field under first name and last name in iPhone contact.
Could any update this?

**Comment by belkevich** [comment]
Hi,
You should add `APContactFieldJob` to `fieldMask`property. Read more [here](https://github.com/Alterplay/APAddressBook/blob/master/README.md).

**Comment by belkevich** [comment]
Feel free to reopen this issue, if you still have problem
