### ISSUE TITLE
Unable to get the address information

### ISSUE THREAD

**Issue by pushian** [Alterplay/APAddressBook#155]
For the contact with the address information, the APContact.addresses is still nil.

**Comment by belkevich** [comment]
Do you set `fieldsMask` with `APContactFieldAddressesWithLabels` or `APContactFieldAddressesOnly`?

**Comment by pushian** [comment]
@belkevich How can I do this setting? I did not see any instruction for this part.

**Comment by belkevich** [comment]
@pushian section **Select contact fields bit-mask** in [Readme](https://github.com/Alterplay/APAddressBook/blob/master/README.md)

**Comment by pushian** [comment]
@belkevich solved, thanks belkevich!

**Comment by belkevich** [comment]
You are welcome!
