### ISSUE TITLE
How can I get google id (social type id)

### ISSUE THREAD

**Issue by Ilesh** [Alterplay/APAddressBook#170]
I sync my google contact with my phone book id and display all the contact in the phonebook. How Can I bifurcation of which is my google contact and others? If you give me any solution it would be great. Thanks for your help.

**Comment by belkevich** [comment]
I don't think it's possible to determine is contact from iphone contacts or from google contacts.
But you can try this:
1) Filter contacts, that have been created after date you sync with google (most of the contacts should be from google)
2) Filter contacts, that have social profile type 'google'
See [README](https://github.com/Alterplay/APAddressBook/blob/master/README.md) to get more information about filtering

**Comment by Ilesh** [comment]
I need google id (Source_Id) of the contacts, Any way to find the google contact id for my address book contact? in Android possible for this way (https://stackoverflow.com/a/26708378/2910061)

**Comment by belkevich** [comment]
Sorry, I don't understand you right at first time.
I've checked types of supported social networks. And unfortunately, there is no support for google in social profiles of iphone contacts.

**Comment by Ilesh** [comment]
Okay @belkevich, If you find anything regarding this, please let me know. Thanks for your time.

**Comment by belkevich** [comment]
You are welcome
