### ISSUE TITLE
'ABRecordRef' is deprecated: first deprecated in iOS 9.0

### ISSUE THREAD

**Issue by sourabhardwaj** [Alterplay/APAddressBook#172]
I am running my app on `iOS 10` or higher deployment target and using `Swift 3.0` and `XCode 9` version. However we are getting below compiler warnings:

`'ABRecordRef' is deprecated: first deprecated in iOS 9.0 - use CNContact, CNGroup, or CNContainer`

`'ABAddressBookRef' is deprecated: first deprecated in iOS 9.0 - use CNContactStore`

Kindly suggest which pod version of the APAddressBook has the updated iOS framework integrated.

Thanks,
~ Sourabh

**Comment by belkevich** [comment]
`APAddressBook` is based on `AddressBook.framework` which is deprecated.
So there is now way to remove this warnings except use new [Contacts API](https://developer.apple.com/documentation/contacts) instead of `APAddressBook`
