### ISSUE TITLE
Address not showing.

### ISSUE THREAD

**Issue by doriansgithub** [Alterplay/APAddressBook#173]
As per the photo, the mapSearch works, but the local addressBook doesn't.
![img_0454](https://user-images.githubusercontent.com/5715600/38462136-1e73a590-3a96-11e8-80b4-4c4e0d8884e1.png)

        case SearchTableSection.addressBook.rawValue:
            let cell:AddressBookSearchCell = self.tableView.dequeueReusableCell(withIdentifier: "AddressBookSearchCell") as! AddressBookSearchCell
            cell.update(with: contacts[indexPath.row])
            return cell
        case SearchTableSection.addressMap.rawValue:
            let cell:AddressMapSearchCell = self.tableView.dequeueReusableCell(withIdentifier: "AddressMapSearchCell") as! AddressMapSearchCell
            cell.mapItem = mapSearchResult[indexPath.row]
            return cell

**Comment by belkevich** [comment]
Do you add the `APContactFieldAddressesWithLabels` field (or `APContactFieldAddressesOnly `) to fields bit-mask of `APAddressBook` instance?

**Comment by doriansgithub** [comment]
You're a genius!  Fixed! Case Closed!

**Comment by belkevich** [comment]
🤣
