### ISSUE TITLE
APAddressBook not updated after changes in AddressBook

### ISSUE THREAD

**Issue by luchivalles** [Alterplay/APAddressBook#28]
I've tried adding and deleting the phone of a contact to see if the changes where refreshed (I'm retrieving contacts whith phone number as in the example given).
The callback was fired when a change like that was produced, but when I called listOfContacts I was receiving the same list of contacts as I had before the change... So I've ended up with this solution:
 
modifying APAddressBookExternalChangeCallback in APAddressBook.m by adding this line as first line:

ABAddressBookRevert(addressBookRef);

and now I obtain the refreshed list of contacts.
Greetings, and congratulations for your job!
Lucía.

**Comment by smokyfire** [comment]
I'm having the same issue, which is quite problematic. The workaround works for me so far:

"modifying APAddressBookExternalChangeCallback in APAddressBook.m by adding this line as first line:

ABAddressBookRevert(addressBookRef);"

**Comment by mixalich7b** [comment]
+1 I have the same issue. Callback runs, but AddressBook returns old contact list.

**Comment by belkevich** [comment]
Fixed. Check out version 0.1.6
