### ISSUE TITLE
Make ABAddressBookRef public?

### ISSUE THREAD

**Issue by philmitchell** [Alterplay/APAddressBook#48]
You keep the wrapped ```ABAddressBookRef``` private, but in order to call ```ABAddressBookRequestAccessWithCompletion```, we need to access it.

If you agree, I'm happy to submit a pull request. Thanks!

**Comment by vdugnist** [comment]
Why you can't just use loadContactsOnQueue:completion:? This method call ABAddressBookRequestAccessWithCompletion.

**Comment by belkevich** [comment]
According to apple documentation 'ABAddressBookRef' should be used in one thread only. So, making it public is not thread safety. Use 'loadContactsOnQueue:completion'
