### ISSUE TITLE
Crashes app when trying startObserveChangesWithCallback

### ISSUE THREAD

**Issue by karmsingh** [Alterplay/APAddressBook#53]
Both in the sample code and app...when you test a change in the Address book access it crashed the app. To replicate:

1.  Deny access to AddressBook..
2. Go into Settings > The app > allow access...app crashed.

**Comment by Krivoblotsky** [comment]
This is expected behavior. iOS sends SIGKILL 9 message to the app when you changes AddressBook permissions, so every app that react to changes in privacy permissions will be killed.

**Comment by karmsingh** [comment]
Hi Krivoblotsky, thanks for the info. That is strange...I tested this with other apps (try snapchat) and they don't crash? Is there a graceful way to handle it?

**Comment by Krivoblotsky** [comment]
I'm pretty sure, that they are crashing as well. I suppose they use UI state restoration to achieve such result, or some relative API.
https://developer.apple.com/library/ios/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/StrategiesforImplementingYourApp/StrategiesforImplementingYourApp.html
