### ISSUE TITLE
JSON encoding

### ISSUE THREAD

**Issue by gurre** [Alterplay/APAddressBook#54]
Maybe it's just lack of knowledge but how can I encode a APContact to JSON in a easy way? 

    NSData *jsonData = [NSJSONSerialization dataWithJSONObject:contacts options:0 error:nil];
    *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Invalid type in JSON write (APContact)'

**Comment by Krivoblotsky** [comment]
No, you can't just pass APContact to NSJSONSerialization. You should serialize APContact first. If you want "an easy way", I suggest to use some 3rd party serialization library. My favorite one is EasyMapping. 
https://github.com/EasyMapping/EasyMapping
