### ISSUE TITLE
APAddressBook module is missing

### ISSUE THREAD

**Issue by arjohnson97** [Alterplay/APAddressBook#56]
As far as I can tell, the pod is installed correctly, however, when I try and use "import APAddressBook", it says no such module.

**Comment by belkevich** [comment]
Please, show provide 'import' code.

**Comment by hitec** [comment]
I am facing the same issue. I just tried the example code and it's giving me an error " No such module"

here is the code

import UIKit
import AddressBook


class displayContactList: UIViewController {
    
    let addressBook = APAddressBook()
    var contactPhoneNames: [String] = []
    var contactPhoneNumbers: [String] = []
    
    
    
    
    override func viewDidLoad() {
        super.viewDidLoad()
      
        
        
        // Do any additional setup after loading the view.
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        
        
        // Dispose of any resources that can be recreated.
    }

**Comment by belkevich** [comment]
Are you using 'APAddressBook/Swift' pod? Also don't forget to import "APAddressBook-Bridging.h" to objective-c bridging file

**Comment by hitec** [comment]
I m using the swift version and Yes I did  import the APAddressBook-Bridging.h to the bridging file. (image attached)

![image](https://cloud.githubusercontent.com/assets/12803166/8044582/99b7b5fe-0dfb-11e5-8459-6bf5f78572c5.png)

**Comment by belkevich** [comment]
Looks like you shouldn't use "import AddressBook". All imports declared in bridging-file available everywhere in project (not sure, actually =)). Try to remove "import"

**Comment by hitec** [comment]
Not sure where you don't want me to use import?  I have attached the code view where I am getting the error.

![image](https://cloud.githubusercontent.com/assets/12803166/8044800/1ca86a70-0dfd-11e5-85eb-b16be5f42f95.png)

**Comment by belkevich** [comment]
I've created simple project and everything works fine for me. If you would like, a can share it with you.
So, I have two versions of what's wrong.
1) You forgot to add bridging file path to project 'build settings'
2) Some trouble with cocoapods. Update cocoapods and drop 'Pods' folder

**Comment by hitec** [comment]
That will be indeed great help if you can share your  sample project. I am really struggling with getting this to work and I am sure that I did miss someting.

**Comment by hitec** [comment]
Ok I found the problem. Just reinstalled  cocopods and it worked fine.  Thank you so much for your prompt help.
