### ISSUE TITLE
Calling APAddressBook.access() after permissions are updated in Settings does not reflect changes.

### ISSUE THREAD

**Issue by NitWitStudios** [Alterplay/APAddressBook#57]
I am trying to alert users when they need to enable permissions for my app to access their Contacts. I call 'loadAddressBookContacts()' in both 'viewDidLoad' and from an observer that listens for UIApplicationDidBecomeActiveNotification (for when a user leaves the app to update the permissions then comes back). 
However, calling 'APAddressBook.access()' after the user has left the app and updated the permissions in settings does not seem to recognize the change and still returns the 'denied' status. Only after re-launching the app does the change get observed. Is this being cached somehow?

    func loadAddressBookContacts()
    {
        // Check if access is denied
        if APAddressBook.access() == APAddressBookAccess.Denied
        {
            self.displayAddressBookPermissionsAlert()
            return
        }
        ...load contacts...
    }

**Comment by henr** [comment]
the same problem

**Comment by NitWitStudios** [comment]
@henr Forgot this issue was open. There is no solution, this is actually an iOS issue. Even using the native AddressBook framework, an app is required to be relaunched after permissions are changed before they are reloaded. Most likely it is a security issue. Sucks, but the only thing you can do is inform the user they need to relaunch the app.
