### ISSUE TITLE
Doesn't with Swift and Cocoapods use_frameworks 

### ISSUE THREAD

**Issue by samuelbeek** [Alterplay/APAddressBook#58]
If I use cocoapods 'use_frameworks' feature, the bridging header isn't included in the package, so it doesn't work. On the surface this is not a big problem, since I can just remove the use_frameworks string from my podfile. However, my other pods are depended on that thing, so it would be nice if there was a way to fix this.

**Comment by bowenisdum** [comment]
i think you can do "import APAddressBook" in the swift file that access it

**Comment by eman3488** [comment]
Im having the same issue. Is there a known solution for this?

**Comment by belkevich** [comment]
Sorry, for delay.
Do you use `pod 'APAddressBook/Swift'` instead of `pod 'APAddressBook'` in Podfile?

**Comment by redi-wassere** [comment]
Thanks for getting back to us @belkevich. Yes, Im using APAddressBook/Swift, and it all is working now. I was being dumb and opening the wrong codeproj vs workspace file in XCode..

**Comment by belkevich** [comment]
@redi-wassere don't blame yourself. I'm doing similar things twice a day 😀

**Comment by samuelbeek** [comment]
Ah, I did the same. Thanks for clarifying @belkevich. Closing the issue.
