### ISSUE TITLE
Reason for missing fields

### ISSUE THREAD

**Issue by ogezue** [Alterplay/APAddressBook#60]
What is the reason why a lot of available fields are missing in your framework? Would you be interested in a pull request that adds the missing fields?

**Comment by belkevich** [comment]
Sorry, for delay.
`APAddresBook` use to be small library for fetching contact's name and phone. And then people send us pull requests with new fields ))
Yes, we still interested in missing fields. But there are 2 problems
1) `APAddressBook` is growing and field mask looks stupid now. We should change this approach to fields in `APAddressBook 0.2.0`.
2) The core of `APAddressBook` (ABAddressBook.framework) is deprecated in iOS 9. And new framework should be included for `APAddressBook 0.2.0`

So, wait for `APAddressBook` 0.2.0 and send us your pull requests!
