### ISSUE TITLE
Thumbnails not loading for contacts

### ISSUE THREAD

**Issue by NitWitStudios** [Alterplay/APAddressBook#61]
I am trying to display the thumbnail images for address book contacts, and for some reason it recently stopped working.
When I use this code with a breakpoint inside the block, it never gets hit:

    if let thumbnail = cell.apContact?.thumbnail
    {
         cell.leftIconImageView.image = thumbnail
    }

I have verified that the contacts do in fact have thumbnails in my native Contacts app. I have also tried to use '.photo' instead of '.thumbnail' and still no luck.
It was working before just fine so not sure why the thumbnails are being ignored now. Everything else (i.e. names, emails, phone numbers) all load up just fine.
I think I updated the pod installation a week or so ago, so not sure if something changed since my initial use a couple months ago.

Any ideas?

**Comment by NitWitStudios** [comment]
Bump! Any thoughts on this?

**Comment by Krivoblotsky** [comment]
Did you use correct APContactFieldMask with APContactFieldThumbnail included?

**Comment by NitWitStudios** [comment]
@Krivoblotsky Yes that ended up being the problem. Apparently the thumbnail mask had been removed. I believe the thought was that the masks were used to filter out and return only contacts that matched them. In reality, the masks just return those items for each contact. Doh!
