### ISSUE TITLE
Contacts Birthday

### ISSUE THREAD

**Issue by RajChanchal** [Alterplay/APAddressBook#62]
Hi, thanks for the great tool. I needed to know if I can get birthday of contacts? My native contacts list do show birthday's of different contacts fetched from Facebook. But I don't see any property in APContact class regarding it.

**Comment by belkevich** [comment]
Hi!
Unfortunately `APAddressBook` doesn't support contact's birthday now

**Comment by belkevich** [comment]
[Done](https://github.com/Alterplay/APAddressBook/releases/tag/0.1.13)
