### ISSUE TITLE
APContact addresses NSArray is always null

### ISSUE THREAD

**Issue by kennyszub** [Alterplay/APAddressBook#70]
Whether a contact has an address or not, I'm always seeing an empty addresses array in the filterBlock.

**Comment by Krivoblotsky** [comment]
Can you, please, share the code of APAddressBook setup and contacts loading?

**Comment by kennyszub** [comment]
I was just doing this:

APAddressBook *addressBook = [[APAddressBook alloc] init];
addressBook.filterBlock = ^BOOL(APContact *contact)
{
    return contact.addresses.count > 0;
};
[addressBook loadContacts:^(NSArray *contacts, NSError *error)
{
    if (!error)
    {
        // contacts array was always empty for me
    }
    else
    {
        // was not encountering any NSError
    }
}];

And I would get an empty array, despite many of my contacts having addresses. When I set a breakpoint in the filter block, I saw other attributes on APContact properly set, but addresses was nil even if the contact had addresses.

I was able get addresses no problem when I just used the core foundation frameworks directly, so I'm fairly certain there's an issue.

**Comment by belkevich** [comment]
You should set `fieldMask` with contact's properties that your app need.
Example:
```objective-c
...
addressBook.fieldsMask = APContactFieldFirstName | APContactFieldLastName | APContactFieldAddresses
...
```

**Comment by aykutt** [comment]
It still continues on my project, the contacts array in debug mode:
contacts	__NSArrayI *	@"320 objects"	0x173a5200
[0]	APContact *	0 key/value pairs	0x1665e790
[1]	APContact *	0 key/value pairs	0x1665e710
[2]	APContact *	0 key/value pairs	0x1665e6c0
...

My code:
```
APAddressBook *addressBook = [[APAddressBook alloc] init];
    addressBook.fieldsMask = APContactFieldFirstName | APContactFieldLastName | APContactFieldPhones | APContactFieldThumbnail;
    [addressBook loadContacts:^(NSArray *contacts, NSError *error)
    {
        if (!error)
        {
            //NSLog ...
        }
        else
        {
            // show error
        }
    }];
```

**Comment by belkevich** [comment]
1) Does `Example` app work correctly on your device/simulator?
2) Do you try to put breakpoint in `APContact` initialization method?

**Comment by aykutt** [comment]
Yes `Example App` worked on phones. I didn't fully understand what happened but it works know.
In the first place, I wasn't assign the result array parameters to `APContact`. So the problem occurs about that I guess.
Thanks @belkevich

**Comment by belkevich** [comment]
You are welcome!
