### ISSUE TITLE
ABAddressBookRegisterExternalChangeCallback doesn't called.

### ISSUE THREAD

**Issue by b2github** [Alterplay/APAddressBook#72]
when I changed 
```
dispatch_async(self.localQueue, ^
            {
                ABAddressBookRegisterExternalChangeCallback(self.addressBook,
                                                            APAddressBookExternalChangeCallback,
                                                            (__bridge void *)(self));
            });
```
to
```
dispatch_async(dispatch_get_main_queue(), ^
            {
                ABAddressBookRegisterExternalChangeCallback(self.addressBook,
                                                            APAddressBookExternalChangeCallback,
                                                            (__bridge void *)(self));
            });
```
then it does call to the callback function but then the other errors will occur.

It looks like that APAddressBookExternalChangeCallback will be called on the thread that registered it then if we call register function with GCD then it can be a problem because we have no idea about how the system create, using and destroy threads for using with queue. 

do you have any idea how to fix it.

cheers

**Comment by belkevich** [comment]
Ok, I'll check it

**Comment by b2github** [comment]
For more information. 
My workaround after changing working queue for ABAddressBookRegisterExternalChangeCallback to main queue is reinitialising (alloc, init) ABAddressBook instance again. The errors are gone until now.

cheers.

**Comment by belkevich** [comment]
Seems you are right.
I've remove local GCD-queue and set 'addressBook' property as atomic.
Check out version 0.1.9
