### ISSUE TITLE
Crash on APContact `imagePropertyFullSize:fromRecord:` on 0.1.7 and 0.1.8

### ISSUE THREAD

**Issue by briankracoff** [Alterplay/APAddressBook#73]
I updated from 0.1.5 to 0.1.8 and now I'm getting a consistent crash on `APContact.m`. I'm going to have to revert back to 0.1.5 for now. It crashes 0.1.7 as well (but not 0.1.6).

![screen shot 2015-06-11 at 2 22 27 pm](https://cloud.githubusercontent.com/assets/1471922/8114837/51272fd0-1045-11e5-8e90-3b61e045c156.png)

**Comment by belkevich** [comment]
Hi!
I've checked the issue. And everything works fine on my phone.
Please, provide details like console output or stack trace.

P.S. Also, you should remember full size images take a lot of memory. And it can be reason of crash

**Comment by briankracoff** [comment]
After doing some investigation, it looks like it's a bug on our end due to multithreading. We're getting the malloc error `malloc: *** error for object _: incorrect checksum for freed object - object was probably modified after being freed.`.

Something must have changed in your dispatching between 0.1.5 and 0.1.6, but we may have been loading the contacts on separate threads causing the crash. It's odd since it used to work fine, but we will fix our end before moving to 0.1.6+. Feel free to close. Thanks!
