### ISSUE TITLE
Crash [APContact enumerateMultiValueOfProperty:fromRecord:withBlock:] 

### ISSUE THREAD

**Issue by DmitryAE** [Alterplay/APAddressBook#75]
Hello Alexey.

I found a bug. 

Contact has no emails/phones (any arrays) but we try to retrieve it. 

swift code to create contact: APContact(recordRef: person, fieldMask: .FirstName | .LastName | .Phones | .Emails) -> 

[APContact enumerateMultiValueOfProperty:fromRecord:withBlock:] method -> 

ABMultiValueRef multiValue = ABRecordCopyValue(recordRef, property);

multiValue is 0x0 in this case but we try to release it at CFRelease(multiValue);

So the the app crashes.

We need something like this:

    if (multiValue != nil) { {
        CFRelease(multiValue);
    }

Thank you for your work!

**Comment by belkevich** [comment]
Hi!
Thank you for feedback. We'll check and fix it.

**Comment by DmitryAE** [comment]
Thanks! :-)

**Comment by adomanico** [comment]
I am also seeing this issue. Any eta on a release with a fix?

**Comment by belkevich** [comment]
Fixed. Checkout version 0.1.11

**Comment by DmitryAE** [comment]
Thanks!
