### ISSUE TITLE
Contact's company always returns nil

### ISSUE THREAD

**Issue by mplaczek** [Alterplay/APAddressBook#79]
Hi, I'm having trouble extracting the company info from my contacts. At the moment I iterate thought the Contacts list and pass a contact to a method to extract the first and last name and concatenate these into a string that is returned. However for entries that have no first and last name I'm trying to return the company instead.
However, contacts[i].company always returns nil

**Comment by belkevich** [comment]
Hi
Do you include `APContactFieldCompany ` in field mask?

**Comment by mplaczek** [comment]
Thank you, that works. Apologies, I did not realise that data would not be returned by default.
