### ISSUE TITLE
startObserveChangesWithCallback doesn't work in my swift project

### ISSUE THREAD

**Issue by lyair1** [Alterplay/APAddressBook#81]
self.addressBook.startObserveChangesWithCallback({() in
                println("Address book change detected")
            })

I added this code to my project, it's never being called. What am I doing wrong?

Thank you very much!

**Comment by belkevich** [comment]
Are you sure have changes in your address book?))
See example app and use it in your code. It works fine with changes.
If it doesn't help, provide more code (`APAddressBook` initialization, calls). And describe how you made changes in device address book.

**Comment by romaincointepas** [comment]
+1, it never get called in Swift.

See below for a potential solution:
http://stackoverflow.com/questions/25346563/address-book-external-change-callback-in-swift-with-c-function-pointers

**Comment by belkevich** [comment]
Thank you, for feedback. I'll check it.

**Comment by laptobbe** [comment]
+1, does not seem to work, have not looked into the workaround yet. Might post a PR when I do.

**Comment by belkevich** [comment]
Fixed in 0.1.12.
I've also updated swift example with 'observe external changes'. You can pull it from `develop` branch now
