### ISSUE TITLE
How we can group based on alphabet?

### ISSUE THREAD

**Issue by datomnurdin** [Alterplay/APAddressBook#89]
How possibility to group all the contact numbers based on alphabet using this library?

![petbook-allcontacts](https://cloud.githubusercontent.com/assets/5416242/9626300/235de8ce-518f-11e5-890a-fe1898333883.png)

**Comment by belkevich** [comment]
Sorry, may be I don't understand your question. Try 'sortDescriptors' property to sort contacts by alphabet.
