### ISSUE TITLE
Sort by firstname: case sensitive

### ISSUE THREAD

**Issue by JonMo** [Alterplay/APAddressBook#92]
Hello,

When i use the sort method by firstnames, It creates two list differentiated by the uppercase and lowercase of the first letter of the firstname, example:
Aaron
Barbara
Mark
Victoria
alfred
charles
jim
nancy

How can i solve this case sensitivity issue? 
Thanks

**Comment by belkevich** [comment]
Hello,

Here is [Apple's NSSortDescriptor guide](https://developer.apple.com/library/ios/documentation/Cocoa/Conceptual/SortDescriptors/Articles/Creating.html#//apple_ref/doc/uid/20001845-SW4). Use case insensitive compare

**Comment by JonMo** [comment]
Great! 
Thank you
