### ISSUE TITLE
Get contact emails

### ISSUE THREAD

**Issue by JordanMontel** [Alterplay/APAddressBook#93]
Hello,

Thanks for your library to save me a lot of time :)

When I do the following code : 

APAddressBook *addressBook = [[APAddressBook alloc] init];
        
        [addressBook loadContacts:^(NSArray *contacts, NSError *error) {
            
            for (APContact *contact in contacts)
            {
                NSLog(@"contact name : %@ - %@", contact.firstName, contact.lastName);
                NSLog(@"%@", contact.emails);
                NSLog(@"%@", contact.phones);
                NSLog(@"\n\n");
            }
        }];

I retrieved all phones numbers per contact but emails are always "null".
I tried to test both device and simulator on iOS 8 and 9.

The code in `APContact` never run inside this test : 

        if (fieldMask & APContactFieldEmails)
        {
            _emails = [self arrayProperty:kABPersonEmailProperty fromRecord:recordRef];
        }

Thank by advance for your answer.

**Comment by belkevich** [comment]
Looks like you forget to set `fieldMask`.
```objective-c
APAddressBook *addressBook = [[APAddressBook alloc] init];
addressBook.fieldsMask = APContactFieldDefault | APContactFieldEmails;
```

Read **Select contact fields bit-mask** section of [readme](https://github.com/Alterplay/APAddressBook/blob/master/README.md);

**Comment by JordanMontel** [comment]
Thank you it works :)
