### ISSUE TITLE
APAddressBook new release

### ISSUE THREAD

**Issue by keith** [Alterplay/APAddressBook#98]
I saw that you just release 0.1.14, but it looks like that tag doesn't contain the fixes from https://github.com/Alterplay/APAddressBook/pull/76

You can see that they are not here https://github.com/Alterplay/APAddressBook/blob/0.1.14/Pod/Core/Public/Models/APContact.h

Would you mind creating a new release off master to fix these?

**Comment by belkevich** [comment]
Version 0.1.14 is a hotfix for 0.1.13. It doesn't include "nullability" pull request.
I'm going to release this feature, generics and big refactoring in 0.2.0 this week.

**Comment by belkevich** [comment]
Done. Read [migration guide](https://github.com/Alterplay/APAddressBook/wiki/0.1.x-to-0.2.x-migration-guide) and update the pod.

**Comment by keith** [comment]
Thanks!
