### ISSUE TITLE
How can I get firstName and add in a Dictionary?

### ISSUE THREAD

**Issue by eduardobonfa** [Alterplay/APAddressBook#99]
HI, I trying to add firstName and phone number in a dictionary so I can deal with it later. So I did this

NSDictionary *contactDictionary = @{
                                              @"firstName" : contact.firstName,
                                              @"middleName" : contact.middleName,
                                              @"lastName" : contact.lastName,
                                              @"phones" : contact.phones,
                                              };
But I get this error:
Property 'firstName' not found on object of type 'APContact'. (and it's TRUE)

but When I try putting contact.name.firstName it doesn`t work either.

What can I do?

**Comment by belkevich** [comment]
Please, share you code of using of `APAddressBook`

**Comment by eduardobonfa** [comment]
This is my code

NSMutableArray* returnContacts;
APContact* contact;

- (void)reloadContacts {
    
    APAddressBook *addressBook = [[APAddressBook alloc] init];
    
    addressBook.fieldsMask = APContactFieldDefault;
    addressBook.sortDescriptors = @[
                                    [NSSortDescriptor sortDescriptorWithKey:@"name.firstName" ascending:YES],
                                    [NSSortDescriptor sortDescriptorWithKey:@"name.lastName" ascending:YES]
                                    ];
    addressBook.filterBlock = ^BOOL(APContact *contact)
    {
        return contact.phones.count > 0;
    };
    [addressBook loadContacts:^(NSArray <APContact *> *contacts, NSError *error) {
        if (!error) {
            for (int i = 0; i < contacts.count; i++){
                contact = [contacts objectAtIndex:i];
                NSDictionary *contactDictionary = @{
                                     @"firstName" : contact.firstName,
                                     @"middleName" : contact.middleName,
                                     @"lastName" : contact.lastName,
                                     @"phones" : contact.phones,
};
            }
            [returnContacts addObject:contactDictionary];
        } else if (error) {
            UIAlertView *alertView = [[UIAlertView alloc] initWithTitle:nil
                                                                message:error.localizedDescription
                                                               delegate:nil
                                                      cancelButtonTitle:@"OK"
                                                      otherButtonTitles:nil];
            [alertView show];
        }
    }];
}

**Comment by belkevich** [comment]
Looks like problem is in
```objective-c
@"firstName" : contact.firstName,
@"middleName" : contact.middleName,
@"lastName" : contact.lastName,
@"phones" : contact.phones,
```
there are no such properties, except `phones`. Use `contact.name.firstName` etc.

**Comment by eduardobonfa** [comment]
if I try it, I get this error

Property 'firstName' cannot be found in forward class object 'APName'

**Comment by belkevich** [comment]
Add `#import <APAddressBook/APName.h>`?

**Comment by eduardobonfa** [comment]
it worked, thank you, sorry I'm new at objective c

**Comment by belkevich** [comment]
It's ok.
Have a nice day!
